### PR TITLE
Use `jaxb-bom`

### PR DESCRIPTION
**Pull request by basil**
Supersedes #17. Addresses [this feedback](https://github.com/jenkinsci/jaxb-plugin/pull/18#discussion_r818815521) by @jglick:

> Is there a BOM we could import?

Yes, there is. In this PR, we import it.

Note that the way the various class files are distributed into JARs (and the group IDs and artifact IDs of those JARs) have changed significantly in recent versions of JAXB (now called Jakarta XML Binding). To convince yourself that this PR is correct, compare the list of classes from the current shipping release JPI (2.3.0.1) with those from the JPI from this PR. Here is the diff, which shows only evolutionary changes (good!), not packaging errors:

```
33s basil ~/src/jenkinsci/jaxb-plugin (bom ⇡) ❯ diff -ruN /tmp/oldclasses /tmp/newclasses
--- /tmp/oldclasses     2022-03-03 13:28:31.801975844 -0800
+++ /tmp/newclasses     2022-03-03 13:28:37.225992699 -0800
@@ -10,6 +10,7 @@
 ./com/sun/istack/localization/Localizer.class
 ./com/sun/istack/localization/NullLocalizable.class
 ./com/sun/istack/logging/Logger.class
+./com/sun/istack/logging/StackHelper.class
 ./com/sun/istack/NotNull.class
 ./com/sun/istack/Nullable.class
 ./com/sun/istack/Pool$Impl.class
@@ -61,27 +62,24 @@
 ./com/sun/xml/bind/marshaller/SAX2DOMEx.class
 ./com/sun/xml/bind/marshaller/XMLWriter.class
 ./com/sun/xml/bind/Messages.class
+./com/sun/xml/bind/StackHelper.class
 ./com/sun/xml/bind/unmarshaller/DOMScanner.class
 ./com/sun/xml/bind/unmarshaller/InfosetScanner.class
 ./com/sun/xml/bind/unmarshaller/Messages.class
 ./com/sun/xml/bind/unmarshaller/Patcher.class
 ./com/sun/xml/bind/util/AttributesImpl.class
-./com/sun/xml/bind/Util.class
+./com/sun/xml/bind/Utils.class
 ./com/sun/xml/bind/util/SecureLoader$1.class
 ./com/sun/xml/bind/util/SecureLoader$2.class
 ./com/sun/xml/bind/util/SecureLoader$3.class
 ./com/sun/xml/bind/util/SecureLoader.class
 ./com/sun/xml/bind/util/ValidationEventLocatorExImpl.class
 ./com/sun/xml/bind/util/Which.class
-./com/sun/xml/bind/v2/bytecode/ClassTailor.class
-./com/sun/xml/bind/v2/bytecode/SecureLoader$1.class
-./com/sun/xml/bind/v2/bytecode/SecureLoader$2.class
-./com/sun/xml/bind/v2/bytecode/SecureLoader$3.class
-./com/sun/xml/bind/v2/bytecode/SecureLoader.class
 ./com/sun/xml/bind/v2/ClassFactory$1.class
 ./com/sun/xml/bind/v2/ClassFactory$2.class
 ./com/sun/xml/bind/v2/ClassFactory.class
 ./com/sun/xml/bind/v2/ContextFactory.class
+./com/sun/xml/bind/v2/JAXBContextFactory.class
 ./com/sun/xml/bind/v2/Messages.class
 ./com/sun/xml/bind/v2/model/annotation/AbstractInlineAnnotationReaderImpl.class
 ./com/sun/xml/bind/v2/model/annotation/AnnotationReader.class
@@ -354,7 +352,6 @@
 ./com/sun/xml/bind/v2/runtime/output/XmlOutputAbstractImpl.class
 ./com/sun/xml/bind/v2/runtime/output/XmlOutput.class
 ./com/sun/xml/bind/v2/runtime/output/XMLStreamWriterOutput$1.class
-./com/sun/xml/bind/v2/runtime/output/XMLStreamWriterOutput$NewLineEscapeHandler.class
 ./com/sun/xml/bind/v2/runtime/output/XMLStreamWriterOutput$XmlStreamOutWriterAdapter.class
 ./com/sun/xml/bind/v2/runtime/output/XMLStreamWriterOutput.class
 ./com/sun/xml/bind/v2/runtime/property/ArrayElementLeafProperty.class
@@ -415,7 +412,6 @@
 ./com/sun/xml/bind/v2/runtime/reflect/ListTransducedAccessorImpl.class
 ./com/sun/xml/bind/v2/runtime/reflect/Messages.class
 ./com/sun/xml/bind/v2/runtime/reflect/NullSafeAccessor.class
-./com/sun/xml/bind/v2/runtime/reflect/opt/AccessorInjector.class
 ./com/sun/xml/bind/v2/runtime/reflect/opt/Bean.class
 ./com/sun/xml/bind/v2/runtime/reflect/opt/Const.class
 ./com/sun/xml/bind/v2/runtime/reflect/opt/FieldAccessor_Boolean.class
@@ -440,8 +436,6 @@
 ./com/sun/xml/bind/v2/runtime/reflect/opt/MethodAccessor_Long.class
 ./com/sun/xml/bind/v2/runtime/reflect/opt/MethodAccessor_Ref.class
 ./com/sun/xml/bind/v2/runtime/reflect/opt/MethodAccessor_Short.class
-./com/sun/xml/bind/v2/runtime/reflect/opt/OptimizedAccessorFactory.class
-./com/sun/xml/bind/v2/runtime/reflect/opt/OptimizedTransducedAccessorFactory.class
 ./com/sun/xml/bind/v2/runtime/reflect/opt/Ref.class
 ./com/sun/xml/bind/v2/runtime/reflect/opt/SecureLoader$1.class
 ./com/sun/xml/bind/v2/runtime/reflect/opt/SecureLoader$2.class
@@ -830,5 +824,7 @@
 ./javax/xml/bind/ValidationException.class
 ./javax/xml/bind/Validator.class
 ./javax/xml/bind/WhiteSpaceProcessor.class
+./META-INF/versions/9/com/sun/istack/logging/StackHelper.class
+./META-INF/versions/9/com/sun/xml/bind/StackHelper.class
 ./META-INF/versions/9/javax/xml/bind/ModuleUtil.class
 ./module-info.class
```

### CODE REVIEW

**Comment by jglick** [comment]
BTW when referring to PR comments just link them plain, to get backlinks and nice preview: https://github.com/jenkinsci/jaxb-plugin/pull/18#discussion_r818815521

**Review by jglick — COMMENTED** [review]
Sounds right, but I have no familiarity with this lib.

**Comment by basil** [comment]
> Sounds right, but I have no familiarity with this lib.

Thank you for the vote of confidence, Jesse.

**Comment by basil** [comment]
@batmat What are the next steps toward the merge and release of this PR?

**Comment by basil** [comment]
@batmat Gentle ping.

**Comment by batmat** [comment]
Hi Basil,
My apologies. TBH I'm wondering whether you becoming a maintainer wouldn't
be the best option. I'm blocking you unintentionally here and that's bad.

WDYT ?

Thanks

Le lun. 14 mars 2022 à 00:07, Basil Crow ***@***.***> a
écrit :

**Comment by basil** [comment]
> TBH I'm wondering whether you becoming a maintainer wouldn't be the best option. I'm blocking you unintentionally here and that's bad. WDYT ?

@batmat I am not interested in becoming a maintainer of this plugin.

**Comment by basil** [comment]
Gentle ping. What are the next steps toward the merge and release of this PR?

**Comment by basil** [comment]
On March 3, @jglick left the following feedback in https://github.com/jenkinsci/jaxb-plugin/pull/18#discussion_r818815521:

> Is there a BOM we could import?

I addressed the feedback in this PR in a timely fashion, yet the PR was not approved.

On March 7, I asked @batmat about the next steps toward the merge and release of this PR. After pinging @batmat on March 13 and April 15, @batmat has not responded in a timely fashion.

On April 25, I ask again: What are the next steps toward the merge and release of this PR?

**Comment by batmat** [comment]
Hi,
I should have been clearer on my message above on the 17th of March where I proposed you become a maintainer too.

I am lacking time and focus to properly review this. I am too rusty to review this w/o yoloing it, hence my proposal.
In other words, I am going to put this plugin up for adoption if that can help clarify.

Thanks

**Comment by batmat** [comment]
Done. Just added the `adopt-this-plugin` label. Cheers

**Comment by basil** [comment]
Thank you for clarifying your intentions, @batmat.

In the past, I have adopted various plugins or components that were not being actively maintained by their original maintainers only for those original maintainers to then complain once I started taking an active role without seeking their approval. I would like to avoid this outcome in the future.

Can you confirm that, if I accepted maintenance of this plugin, you would not have an issue with me taking an active role (i.e., making code changes and releases without your approval)?

Thank you,
Basil

**Comment by batmat** [comment]
Yes. You can and should feel free to release without my ascent. I know you
care about users, so I won't be worried here that we would break them
inconsiderately.

Thanks

Le lun. 25 avr. 2022 à 16:21, Basil Crow ***@***.***> a
écrit :

**Comment by jglick** [comment]
Has this been replaced by something else?

**Comment by basil** [comment]
The use of `jaxb-bom`? It has not. I decided to avoid `jaxb-bom`, because it would have forced us to use the new Jakarta group ID and artifact ID for JAXB API. Unfortunately, like Activation and JavaMail this is yet another example whether the new Jakarta group ID and artifact ID were used for the older `javax` package namespace for a few releases before being switched to the new `jakarta` package namespace for later releases, which makes life complicated with Maven Enforcer. Simpler to stay on the older non-Jakarta group ID and artifact ID when we want the older `javax` package namespace, even if that means being a few minor versions behind on the JAXB API. I did the same thing for Activation and JavaMail.

**Comment by basil** [comment]
BTW I never wanted to use `jaxb-bom` in the first place due to this reason. I just did it hoping to pass your code review, a strategy which turned out to be pointless since you never approved the change after I made the changes you requested.

**Pull request closed without merging**
